### ISSUE TITLE
Unsure how to add food_items to a parties order from the orders/new page with default options

### ISSUE THREAD

**Issue by AlanRice93** [AlanRice93/Happy_Waiter-#1]
#User Story
  - As a user when I click on the "add order to this party" button I want to be redirected to the orders/new page to create a new order with the parameter "party_id" already completed.

#Test Statement 
-When I click on "add a food" from the parties/:id page, it should send me to the orders/new page but with the parameter "which party do you want to assign this order to" already filled out.

#Context
 -I  am having some trouble connecting the "parties/:id" page to the "orders/new" page. When at the "parties/:id" page, I can see a full list of the foods that the party has ordered as well as their size, etc. When I click "add food", I am sent to the "orders/new" page. While I can manually fill in the "food_item" and "party_id" parameters, I want the "party_id" parameter to already be filled out. Since I am coming from the page for a specific group I am attempting to see if there is a way to grab this information and pass it along to the "orders/new" page, or if there is a different erb page I should create to handle this task.

**Comment by amadden80** [comment]
*in person*
