### ISSUE TITLE
Trying to load query information from one page to another 

### ISSUE THREAD

**Issue by AlanRice93** [AlanRice93/Happy_Waiter-#2]
#User Story
-As a user, I want to click on a food order and be sent to a page to edit that specific order, with the "food_type" and "party_number" with default values. 

#Test Statement 
-When I am on /parties/6 page and I click on "bacon", I should be brought to a "orders/edit" page that has  the default values of "partyid=6" and "food_type="bacon" completed. 

#Context
-With Andrew's guidance I was able to get the first party of this problem working in a different context. I recycled the code from that section so that now I have the party-id automatically adjusting the default to the correct party. I have been trying to get the food item to do the same but am having difficulties doing so. No value is being carried over in the controller, and I believe this might be because in my erb file the food_type does not have a @ before it, but I do not see how I can add this.

**Comment by emilylordahl** [comment]
Yo! What's the state of this issue?

**Comment by emilylordahl** [comment]
*In person*
