### ISSUE TITLE
Iterating over a database => getting a ruby for loop to skip over certain values 

### ISSUE THREAD

**Issue by AlanRice93** [AlanRice93/Happy_Waiter-#3]
#User Story 
 - As a user I want to see which tables are occupied and which ones are not. 

#Test 
 - I can click on any table (red if occupied, grey if not) and be sent to their respective pages. I can then double check any of these values in the databse to assure that they are correct. 
 
#Context 
-I am creating a visual representation of which tables are occupied currently and which ones are not. I am checking this by running a loop which looks through my "parties database" and says, "if there is a party with this table_id, that means its occupied" and if no party has that table_id, it marks it as "unoccupied." I also have a feature that check if the party has paid their bill in this loop. So if a party has a table_id of the selected table BUT HAS PAID THEIR BILL, then I know that this was a past party and the table is now open (I don't want to delete my parties from the database every time I close out a party). This issue I am attempting to solve is that the loop only picks up on the FIRST party with that corresponding table_id (i.e. if I have a party with table_id 7 that has already paid, the conditional marks this automatically as "table 7 is therefore unoccupied" without checking if there is another party that has this same table_id that HAS NOT paid yet. I wish, for every check of a table id, for the loop to go through all the parties with that table_id, rather than only processing the first party with that table_id that it finds.

**Comment by amadden80** [comment]
*in person*
